# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  browser-tools: circleci/browser-tools@1.4.6
  slack: circleci/slack@4.12.5

jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: cimg/openjdk:17.0.0-browsers
        environment:
          ## this enables colors in the output
          TERM: xterm
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      
      - run: java  --version
      #- browser-tools/install-browser-tools
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: mvn clean test -DsuiteXmlFile=testNG_MartinaSeminara.xml
      - slack/notify:
          event: always
          
# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  sanity_tests: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - one
