name: e2e pipeline
run-name: Build, Deploy, Test - from user @${{ github.actor }}

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 15
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '1.15'
          cache: maven
          
      - name: Run Unit Tests
        run: mvn test
